# .github/workflows/chromatic.yml
# name of our action
name: 'Chromatic Deployment'
# the event that will trigger the action, do this on push
on: push

# what the action will do, declare the job, which itself consists of multiple steps
jobs:
    test:
        # the operating system it will run on, declare the conditions, or the foundation for the job
        runs-on: ubuntu-latest
        # the list of steps that the action will go through
        steps:
            - uses: actions/checkout@v1
            - run: yarn
            - uses: chromaui/action@v1
              # options required to the GitHub chromatic action
              # required for this uses (chromaui/action@v1) only
              with:
                  # our project token, to see how to obtain it
                  # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
                  projectToken: 7r3evtg9093
                  token: ${{ secrets.GITHUB_TOKEN }}
